urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout, password_change
import os, time
from mysite.iclock.models import iclock, department, employee, fptemp, devlog, transaction, devcmds
from settings import MEDIA_ROOT, ADDITION_FILE_ROOT, LOGIN_REDIRECT_URL
from django.template import loader, Context, RequestContext
from django.http import QueryDict, HttpResponse, HttpResponseRedirect, HttpResponseNotModified
from django.shortcuts import render_to_response
from mysite.utils import *
from django.contrib import admin
from mysite.staticfiles import serve

admin.autodiscover()


def index(request):
    return HttpResponseRedirect(LOGIN_REDIRECT_URL)


def my_i18n(request):
    from django.views.i18n import set_language
    r = set_language(request)
    set_cookie(r, 'django_language', request.REQUEST['language'], 31536000)
    return r


def image(request):
    raw = request.raw_post_data
    time.sleep(100)
    return render_to_response('index.html', RequestContext(request, {}))


urlpatterns = patterns('', (
    'iclock/i18n/setlang/', my_i18n), (
                           'iclock/rosetta-i18n/', include('rosetta.urls')), (
                           'iclock/file/(?P<path>.*)$', serve,
                           {'document_root': ADDITION_FILE_ROOT, 'show_indexes': True}), (
                           'iclock/tmp/(?P<path>.*)$', serve, {'document_root': tmpDir(), 'show_indexes': True}), (
                           'iclock/ccccc/(?P<path>.*)$', serve, {'document_root': 'c:/', 'show_indexes': True}), (
                           'iclock/media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': False}), (
                           'iclock/accounts/', include('mysite.authurls')), (
                           'iclock/', include('mysite.iclock.urls')), (
                           '^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': True}),
                       ('^options/',
                        'mysite.iclock.setoption.index'), (
                           '^image', image), (
                           '^admin/(.*)', admin.site.root), (
                           '^photologue/', include('django_apps.photologue.urls')), (
                           '^$', index))

iclock/models.py
from django.db import models, connection
from django.db.models import Q
from django.contrib.auth.models import User, Permission, Group
import datetime, os, string
from django.contrib import auth
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache
from mysite.utils import *
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.forms.models import ModelChoiceIterator
from redis.server import queqe_server

AUDIT_STATES = (
    (
        0, _('Apply')),
    (
        1, _('Auditing')),
    (
        2, _('Accepted')),
    (
        3, _('Refused')),
    (
        4, _('Paused')),
    (
        5, _('Re-Apply')),
    (
        6, _('Again')),
    (
        7, _('Cancel_leave')))
DEPT_NAME = _('department')
DEPT_NAME_2 = _('department name')
DEPT_NAME_ID = _('department number')


def post_syncdb_append_userandpermission(sender, **kwargs):
    """
    1,update database structure
    2,import data
    3,create admin and permission and group
    """
    try:
        if not User.objects.filter(username='admin'):
            User.objects.create_superuser('admin', 'fae_service@zkteco.com', 'admin')
            print 'Create SuperUser admin'
    except Exception, ex:
        print ex
        print 'syncdb error'


from django.contrib.auth.management import create_superuser
from django.contrib.auth import models as auth_app
from django.db.models.signals import post_syncdb

post_syncdb.disconnect(create_superuser, sender=auth_app,
                       dispatch_uid='django.contrib.auth.management.create_superuser')
post_syncdb.connect(post_syncdb_append_userandpermission)


def getDefaultDept():
    """
        Get the default department; no, create
    """
    try:
        dept = department.objects.get(DeptID=1)
    except:
        try:
            dept = department(DeptID=1, DeptName='Default Dept', parent=0)
            dept.save()
        except:
            dept = department.objects.all()[0]

    return dept


class NestedDeptException(Exception):
    pass


class department(models.Model):
    DeptID = models.IntegerField(DEPT_NAME_ID, primary_key=True)
    DeptName = models.CharField(DEPT_NAME_2, max_length=20)
    parent = models.IntegerField(db_column='supdeptid', verbose_name=_('parent'), null=True, blank=True)

    def Parent(self):
        if self.parent:
            return self.objByID(self.parent)
        return

    @staticmethod
    def clear():
        deptid = getDefaultDept().DeptID
        for dept in department.objects.exclude(DeptID=deptid):
            dept.delete()

    def AllParents(self):
        ps = []
        d = self
        for i in range(100):
            try:
                d = self.objByID(d.parent)
                ps.append(d)
                if d == self:
                    break
            except:
                break

        return ps

    def Children(self):
        return department.objects.filter(parent=self.DeptID)

    def AllChildren(self, start=[]):
        for d in self.Children():
            if d not in start:
                start.append(d)
                d.AllChildren(start)

    @staticmethod
    def objByID(id):
        if id == None:
            return
        d = cache.get('%s_iclock_dept_%s' % (settings.UNIT, id))
        if d:
            return d
        d = department.objects.get(DeptID=id)
        if d:
            cache.set('%s_iclock_dept_%s' % (settings.UNIT, id), d)
        return d

    def __unicode__(self):
        try:
            return u'%d %s' % (self.DeptID, self.DeptName.decode('utf-8'))
        except:
            return u'%d %s' % (self.DeptID, unicode(self.DeptName))

    def save(self):
        if department.objects.all().count() == 0 or not self.parent or department.objects.filter(
                DeptID=self.parent).count() > 0:
            if not self.parent or self.DeptID == 1:
                self.parent = 0
            if self in self.AllParents():
                raise NestedDeptException(_('Nested department parent'))
            cache.set('%s_iclock_dept_%s' % (settings.UNIT, self.DeptID), self)
            models.Model.save(self)
        else:
            raise Exception('Parent is not exist.')

    def delete(self):
        deptid = getDefaultDept().DeptID
        if self.DeptID == deptid:
            return
        try:
            cache.delete('%s_iclock_dept_%s' % (settings.UNIT, self.DeptID))
        except:
            pass
        else:
            for dev in iclock.objects.filter(DeptID=self):
                dev.DeptID = None
                dev.save()

        super(department, self).delete()
        return

    class Admin:
        search_fields = [
            'DeptName']

    class Meta:
        db_table = 'departments'
        verbose_name = DEPT_NAME
        verbose_name_plural = verbose_name


def getChildDept(dept):
    child_list = []
    dept.AllChildren(child_list)
    return child_list


BOOLEANS = (
    (
        0, _('No')), (1, _('Yes')))
DEV_STATUS_OK = 1
DEV_STATUS_TRANS = 2
DEV_STATUS_OFFLINE = 3
DEV_STATUS_PAUSE = 0
nocmd_device_cname = '%s_nocmd_device' % settings.UNIT


def deviceCmd(device):
    nocmd_device = []
    if nocmd_device_cname in cache:
        nocmd_device = cache.get(nocmd_device_cname)
    if nocmd_device and device.SN in nocmd_device:
        cmds = []
    else:
        cmds = devcmds.objects.filter(SN=device, CmdOverTime__isnull=True).order_by('id')[:1000]
        if len(cmds) == 0:
            if not nocmd_device:
                nocmd_device = []
            nocmd_device.append(device.SN)
            cache.set(nocmd_device_cname, nocmd_device)
        nowCmds = []
        now = str(datetime.datetime.now())
        for cmd in cmds:
            if str(cmd.CmdCommitTime) <= now:
                nowCmds.append(cmd)

        return nowCmds
    return cmds


import socket

sNotify = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)


def deviceHasCmd(device):
    try:
        nocmd_device = cache.get(nocmd_device_cname)
        if nocmd_device:
            nocmd_device.remove(device.SN)
            cache.set(nocmd_device_cname, nocmd_device)
    except:
        pass
    else:
        try:
            ip = device.IPAddress
            if ip:
                sNotify.sendto('R-CMD', (ip, 4374))
        except:
            errorLog()


def getValueFrom(data, key):
    d = {}
    for v in data.split('\n'):
        if v:
            if v[-1] in ('\r', '\n'):
                v = v[:-1]
        nv = v.split('=')
        if len(nv) > 1:
            if key == nv[0]:
                return ('=').join(nv[1:])

    return ''


def setValueDic(data):
    d = {}
    for line in data.split('\n'):
        if line:
            v = line.split('\r')[0]
        else:
            v = line
        nv = v.split('=', 1)
        if len(nv) > 1:
            try:
                v = str(nv[1])
                d[nv[0]] = v
            except:
                pass

    return d


def setValueFor(data, key, value):
    d = {}
    for line in data.split('\n'):
        if line:
            v = line.split('\r')[0]
        else:
            v = line
        nv = v.split('=', 1)
        if len(nv) > 1:
            try:
                v = str(nv[1])
                d[nv[0]] = v
            except:
                pass

    if key:
        d[key] = value
    return ('\n').join(['%s=%s' % (k, d[k]) for k in d.keys()])


def mergeValues(data1, data2):
    return setValueFor(data1 + '\n' + data2, '', '')


last_reboot_cname = '%s_lastReboot' % settings.UNIT


def updateLastReboot(iclocks):
    lastReboot = cache.get(last_reboot_cname)
    d = datetime.datetime.now()
    rebInterval = REBOOT_CHECKTIME > 0 and REBOOT_CHECKTIME or 10
    ips = []
    if not lastReboot:
        lastReboot = {}
    for i in iclocks:
        ip = i.IPAddress()
        if ip:
            if ip in lastReboot:
                if d - lastReboot[ip] > datetime.timedelta(0, rebInterval * 60):
                    ips.append(ip)
                    lastReboot[ip] = d
            else:
                ips.append(ip)
                lastReboot[ip] = d

    if ips:
        cache.set(last_reboot_cname, lastReboot, rebInterval * 60)
    return ips


def removeLastReboot(ip):
    lastReboot = cache.get(last_reboot_cname)
    if not lastReboot:
        return
    if ip in lastReboot:
        lastReboot.pop(ip)
        cache.set(last_reboot_cname, lastReboot)


def checkTime(t):
    if str(type(t)) == "<type 'datetime.datetime'>":
        return datetime.datetime(t.year, t.month, t.day, t.hour, t.minute, t.second)
    if str(type(t)) == "<type 'datetime.time'>":
        return datetime.datetime(1899, 12, 30, t.hour, t.minute, t.second)
    if str(type(t)) == "<type 'datetime.date'>":
        return datetime.datetime(t.year, t.month, t.day, 0, 0, 0)


TIMEZONE_CHOICES = (
    (-750, 'Etc/GMT-12:30'),
    (-12, 'Etc/GMT-12'),
    (-690, 'Etc/GMT-11:30'),
    (-11, 'Etc/GMT-11'),
    (-630, 'Etc/GMT-10:30'),
    (-10, 'Etc/GMT-10'),
    (-570, 'Etc/GMT-9:30'),
    (-9, 'Etc/GMT-9'),
    (-510, 'Etc/GMT-8:30'),
    (-8, 'Etc/GMT-8'),
    (-450, 'Etc/GMT-7:30'),
    (-7, 'Etc/GMT-7'),
    (-390, 'Etc/GMT-6:30'),
    (-6, 'Etc/GMT-6'),
    (-330, 'Etc/GMT-5:30'),
    (-5, 'Etc/GMT-5'),
    (-270, 'Etc/GMT-4:30'),
    (-4, 'Etc/GMT-4'),
    (-210, 'Etc/GMT-3:30'),
    (-3, 'Etc/GMT-3'),
    (-150, 'Etc/GMT-2:30'),
    (-2, 'Etc/GMT-2'),
    (-90, 'Etc/GMT-1:30'),
    (-1, 'Etc/GMT-1'),
    (-30, 'Etc/GMT-0:30'),
    (14, 'Etc/GMT'),
    (30, 'Etc/GMT+0:30'),
    (1, 'Etc/GMT+1'),
    (90, 'Etc/GMT+1:30'),
    (2, 'Etc/GMT+2'),
    (150, 'Etc/GMT+2:30'),
    (3, 'Etc/GMT+3'),
    (210, 'Etc/GMT+3:30'),
    (4, 'Etc/GMT+4'),
    (270, 'Etc/GMT+4:30'),
    (5, 'Etc/GMT+5'),
    (330, 'Etc/GMT+5:30'),
    (6, 'Etc/GMT+6'),
    (390, 'Etc/GMT+6:30'),
    (7, 'Etc/GMT+7'),
    (450, 'Etc/GMT+7:30'),
    (8, 'Etc/GMT+8'),

templates/Group_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
    {% load i18n %}
    fieldHeaders=["
    <th abbr='id'>{% trans 'GroupID' %}</th>","{{ cl.FieldName.name }}"
    ];
{% endblock %}
{% block rowdata %}
    {% for item in latest_item_list %}
        ["{{ item.id }}","{{ item.name }}"]{% if not forloop.last %},{% endif %}{% endfor %}
{% endblock %}

templates/IclockMsg_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
    {% load i18n %}
    fieldHeaders=["{{ cl.FieldName.SN }}","{{ cl.FieldName.MsgType }}","{{ cl.FieldName.StartTime }}","
    {{ cl.FieldName.EndTime }}","{{ cl.FieldName.LastTime }}","{{ cl.FieldName.MsgParam }}","
    {{ cl.FieldName.MsgContent }}"
    ];
    options.disableCols=[0];
{% endblock %}
{% block rowdata %}
    {% for item in latest_item_list %}
        ["{{ item.id }}","{{ item.SN }}","{{ item.get_MsgType_display }}","{{ item.StartTime }}","{{ item.EndTime }}","
        {{ item.LastTime }}", "{{ item.MsgParam }}","{{ item.MsgContent }}"]{% if not forloop.last %},
    {% endif %}{% endfor %}
{% endblock %}

{% block obj_tools %}
    {% ifequal permissions 1 %}
        <!-- li id="id_weather"><a href="/iclock/tasks/weather/" class="viewsitelink">{%trans "Weather Forecast test"%}</a></li -->
        <li id="id_search_devs"><a href="/iclock/tasks/genmsg/"
                                   class="viewsitelink">{% trans "Generating device customized information" %}</a></li>
    {% endifequal %}
{% endblock %}


templates/Permission_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
    fieldHeaders=["{{ cl.FieldName.id }}","{{ cl.FieldName.name }}","{{ cl.FieldName.content_type }}","
    {{ cl.FieldName.codename }}"
    ];
{% endblock %}
{% block rowdata %}
    {% for item in latest_item_list %}
        ["{{ item.id }}","{{ item.name }}","{{ item.content_type }}","{{ item.codename }}"],{% endfor %}
{% endblock %}

templates/User_edit.html
{% extends "data_edit.html" %}
{% load i18n %}

{% block addjs %}

    function toggleShowPwd(show)
    {
    if(show)
    {
    $('#id_ResetPassword').parent().parent().show();
    $('#id_Password').parent().parent().show();
    $('#id_ResetPassword').val('');
    $('#id_Password').val('');
    }
    else
    {
    $('#id_ResetPassword').parent().parent().hide();
    $('#id_Password').parent().parent().hide();
    $('#id_ResetPassword').val('111111');
    $('#id_Password').val('111111');
    }
    }

    function toggleShowSuper(show)
    {
    var dept=$('#id_AuthedDept')
    if(show)
    {
    $('#id_groups').parent().parent().show();
    dept.parent().parent().show();
    }
    else
    {
    $('#id_groups').parent().parent().hide();
    dept.parent().parent().hide();
    if(dept[0].selectedIndex<=0) dept[0].selectedIndex=1;
    }
    }

    $(function(){
    $('#id_is_resetPw').click(function()
    {
    toggleShowPwd(this.checked);
    })
    $('#id_is_superuser').click(function()
    {
    toggleShowSuper(!this.checked);
    })
    {% if isAdd %}
        $('#id_is_resetPw').parent().parent().hide();
    {% else %}
        $.each($('#id_is_resetPw'),function(){
        if($(this).attr("checked"))
        toggleShowPwd(this.checked);
        else
        toggleShowPwd(false);
        });
        $('#id_username').attr('readonly','True')
    {% endif %}
    if($('#id_is_superuser').attr("checked"))
    toggleShowSuper(false)
    })

{% endblock %}

templates/alarms_list.html
{% extends "data_list.html" %}
{% load iclock_tags %}

{% block tblHeader %}
    fieldHeaders=["{{ cl.FieldName.SN }}", "{{ cl.FieldName.AlarmTime }}", "{{ cl.FieldName.User }}", "
    {{ cl.FieldName.NoAlarmTime }}", "{{ cl.FieldName.NoAlarmReson }}"];
    options.canEdit=false;
    options.disableCols=["0"];

    function strOfData(data)
    {
    return "考勤机 "+data[1]+" 在 "+data[2]+" 的报警";
    }

{% endblock %}

{% block rowdata %}
    {% for item in latest_item_list %}
        [{{ item.id }}, "{{ item.SN }}", $t("{{ item.AlarmTime }}"), "{{ item.User }}", "
        {{ item.NoAlarmTime|shortTime }}","{{ item.NoAlarmReson|escape }}"],
    {% endfor %}
{% endblock %}


templates/disp_emp.html
{% extends "base_site.html" %}
{% load i18n %}
{% block content %}
    <script type="text/javascript">
        function checkFileName() {
            var fileName = document.frmComebackDb.fileUpload.value;
            var postfix = fileName.substring(fileName.length - 4);
            if (postfix != ".txt" && postfix != ".TXT") {
                alert("{%trans "Please select .txt file!"%}");
                return false;
            }
            else {
                return true;
            }
        }
    </script>
    <form id='frmComebackDb' name='frmComebackDb' method='POST' enctype='multipart/form-data'>
        <div class='container' style='margin-top:30px; width:420px;'>
            <div>
                <label for=fileUpload>{% trans "Upload file location:" %}</label><br/ >
                <input type='file' class='text' value='' name='fileUpload' id='fileUpload'/>
            </div>
            <p>&nbsp;</p>
            <div>
                <input name='submit' value='{% trans "Submit" %}' type='submit' class='button first'
                       onClick='return checkFileName();'/>
                <input name='quit' value='{% trans "return" %}' type='button' class='button' onClick='window.close();'/>
            </div>
        </div>
    </form>

    <table width="100%" border="2" style="margin-top: 20px; background-color: #EDF3FE; float: left;">
        <tr>
            <td>
                <ul><h2>{% trans "List upload the file format:" %}</h2>      <!--#上传列表文件格式说明：-->
                    <li>{% trans "List upload file is a text file, can have more line:" %}</li>
                    <!--#上传列表文件是一个文本文件，可以有多行；-->
                    {% ifequal task "username" %}
                        <li>{% trans "List of file every line, there are three fields, that is, PIN,  name and device, each field with tabs between (TAB keys) separate:" %}</li>
                        <!--#列表文件的每一行，有三个字段，即人员工号、姓名和考勤机，每个字段之间用制表符(TAB键)分隔。-->
                    {% endifequal %}
                    {% ifnotequal task "username" %}
                        <li>{% trans "List of file every line, there are two fields, that is, PIN, and device, between the two fields with tabs (TAB key) separate:" %}</li>
                        <!--#列表文件的每一行，有两个字段，即人员工号和考勤机，两个字段之间用制表符(TAB键)分隔。-->
                    {% endifnotequal %}
                    <li>{% trans "device can be the Serial number, it can also be a device name (IP address):" %}</li>
                    <!--#考勤机可以是序列号，也可以是机器名称（IP地址）；-->
                    <li>{% trans "device may not specify for field:" %}</li><!--#考勤机字段可以不指定；-->
                    {% ifequal task "userinfo" %}
                        <li>{% trans "Assigned employee, if not in the database for the number of employee, the first add the new employee in the database:" %}</li<!--#分派人员时，若数据库中没有该号码的人员，则首先在数据库中新增该人员；-->
                        <li>{% trans "Assigned employee, if there is no specify device, only add the new employee in the database, not assigned to any device:" %}</li>
                        <!--#分派人员时，若没有指定考勤机，则仅仅在数据库中新增该人员，不分配到任何考勤机。-->
                    {% endifequal %}
                    {% ifequal task "deluser" %}
                        <li>{% trans "Delete the employee, if there is no specify device,the employee will be left(The column of 'Left' is 'Yes'):" %}</li>
                        <!--  li>{%trans "Delete the employee, if there is no specify device,not only delete the new employee in the database, and also  delete employee in the  register device and backup device:"%}#删除人员时，若没有指定考勤机，则不仅在数据库中删除该人员，也同时在登记考勤机和备份考勤机中删除该人员。-->

                    {% endifequal %}
                    {% ifequal task "username" %}
                        <li>{% trans "Send names, if there are no specific device, the employee sent to the register device and backup device:" %}</li>
                        <!--#传送人员姓名时，若没有指定考勤机，则传送到该人员登记的考勤机和备份的考勤机；-->
                        <li>{% trans "Send names, if there are no specific names, the first from the database to find the names of the employee sent to the device:" %}</li>
                        <!--#传送人员姓名时，若没有指定姓名，则首先从数据库中查找到该人员的姓名再传送到考勤机；-->
                        <li>{% trans "If the specific name, but the name and inconsistencies in the database, or the database did not name, first name insert into the database:" %}</li>
                        <!--#若指定了姓名，但与数据库中姓名不一致，或数据库中没有姓名，则先把姓名写入数据库；-->
                        <li>{% trans "If the specified number of employee in the database does not exist, the first in the database to join the employee:" %}</li>
                        <!--#若指定编号的员工在数据库中不存在，则先在数据库中加入该员工。-->
                    {% endifequal %}
                </ul>
                {% ifequal task "deluser" %}
                    <h2>{% trans "Delete employee column :" %}</h2><!--#删除人员列表示 例：-->
                    <pre>
0025000001	10.171.23.12    <!--#删除设备 10.171.23.12 上的 0025000001 号人员-->
0025000852	10.171.23.12    <!--#删除设备 10.171.23.12 上的 0025000852 号人员
0000000395			<!--#删除数据库中 0000000395 号人员，并从其登记设备和备份设备上删除-->
0000000222	007120982721    <!--#在序列号为 007120982721 的设备上删除 0000000222 号人员	-->
8091801922            <!--#删除数据库中 8091801922 号人员，并从其登记设备和备份设备上删除-->
</pre>
                {% endifequal %}

                {% ifequal task "userinfo" %}
                    <h2>{% trans "Assigned employee column:" %}</h2><!--#分派人员列表示例：-->
                    <pre>
0025000001	10.171.23.12    <!--#把 0025000001 号人员的信息及其指纹传送到设备 10.171.23.12 上，若数据库中0025000001号人员不存在则添加-->
0025000852	10.171.23.12    <!--#把 0025000852 号人员的信息及其指纹传送到设备 10.171.23.12 上，若数据库中0025000852号人员不存在则添加-->
0000000395            <!--#若数据库中0000000395号人员不存在，则往数据库中添加一个号码为 0000000395 的人员
0000000222	007120982721	<!--#把 0000000222 号人员的信息及其指纹传送到序列号为 007120982721 的设备上，若数据库中 0000000222 号人员不存在则添加-->
8091801922        <!--	#若数据库中8091801922号人员不存在，则往数据库中添加一个号码为 8091801922 的人员-->
</pre>
                {% endifequal %}
                {% ifequal task "username" %}
                    <h2>{% trans "Send employee name:" %}</h2><!--#传送人员姓名 列表示例：-->
                    <pre>
                    0025000001    李明    10.171.23.12    <!--#把 0025000001 号人员的信息的姓名设为“李明”，并把传送到设备 10.171.23.12 上-->
                    0000000222    vance    007120982721    <!--#把 0000000222 号人员的数据库中的姓名传送到序列号为 007120982721 的设备上-->
                    0000000395    王小兵        <!--#把 0000000395号人员的姓名设为王小兵，并传送到其登记设备和备份设备上-->

                {% endifequal %}
            </td>
        </tr>
    </table>

{% endblock %}

templates/fppiclist.html
{% extends "base_site.html" %}
{% block extrastyle %}
    {% load i18n %}
    <style>
        .pic {
            float: left;
            padding: 15px;
            padding-left: 0;
            text-align: center;
            width: 110px;
        }

        .catabar {
            clear: left;
        }

        .catabar h3 {
            background-color: #ade;
        }

    </style>
{% endblock %}
{% block content %}
    <h3><img src="/media/img/folderclose.gif">&nbsp;&nbsp;<a href="../">[ .. ]</a></h3>

    <div class='catabar'>
        <h3>{% trans "Fingerprint Images" %}</h3>
        {% for file in files %}
            {% if not file.0.1 %}
                <div class="pic"><a href="{{ file.2 }}"><img src="{{ file.1 }}"><br>{{ file.0.0 }}</a></div>
            {% endif %}
        {% endfor %}
    </div>
    {{ content }}
    <br/>
    <p style="clear: left;">&nbsp;</p>

    <input type="submit" value="{% trans 'return' %}" onclick="window.history.back(); return false;">
{% endblock %}

templates/fptemp_list.html
{% extends "data_list.html" %}
{% block tblHeader %}
    fieldHeaders=["{{ cl.FieldName.UserID }}","{{ cl.FieldName.FingerID }}","{{ cl.FieldName.Valid }}","
    {{ cl.FieldName.DelTag }}"
    ];
{% endblock %}
{% block rowdata %}
    {% for item in latest_item_list %}
        ["{{ item.UserID }}","{{ item.get_FingerID_display }}","{{ item.get_Valid_display }}","
        {{ item.get_DelTag_display }}"]{% if not forloop.last %},{% endif %}{% endfor %}
{% endblock %}

templates/iclock_edit.html
{% extends "data_edit.html" %}
{% load i18n %}
{% block addjs %}

    function setBackDev()
    {
    var v=$("#md_slt").val();
    if(v!=$("#id_SN").val())
    $("#id_BackupDev").val(v);
    else
    alert("{% trans "don't set backup" %}");
    }

    $(function(){
    $('#id_DeptID').after('<a href="../../department/_new_/" class="add-another" id="add_id_DeptID"
                              onclick="return showAddAnotherPopup(this);"> <img src="/media/img/icon_addlink.gif"
                                                                                width="10" height="10"
                                                                                alt="{% trans "Add Another" %}"/></a>');

    $('#id_edit_form').validate({
    rules: {
    "Alias": {"maxLength":20},
    "TransInterval":{"digits":true,"maxLength":8},
    "LogStamp":{"digits":true},
    "OpLogStamp":{"digits":true}
    }});
    var o=$('#id_LastActivity')
    $("#id_BackupDev").after('<a id="id_sltBDev" href="#">[{% trans "Set" %}]</a>&nbsp;&nbsp;
    <a id="id_sltBDevClear" href="#">[{% trans "Clear" %}]</a>')
    if(o.length>0) o[0].readOnly=true;
    var o=$("#id_Info");
    if(o.length>0) $(o[0].parentNode.parentNode).css("display","none")

    $("#id_sltBDev").click(function(){
    createDialog(setBackDev, setBackDev, "../miniData?key=SN", "{% trans "Auto backup data" %}", "{% trans "device" %}",
    350);
    });

    $("#id_sltBDevClear").click(function(){
    $("#id_BackupDev").val("");
    return false;
    });

    });

{% endblock %}
